# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_wav_dr <- function(path) {
    .Call(`_wav_read_wav_dr`, path)
}

write_wav_int <- function(x, path, sample_rate = 44100L, bit_depth = 16L) {
    .Call(`_wav_write_wav_int`, x, path, sample_rate, bit_depth)
}

write_wav_dbl <- function(x, path, sample_rate = 44100L, bit_depth = 32L) {
    .Call(`_wav_write_wav_dbl`, x, path, sample_rate, bit_depth)
}

